# Generated by Django 4.1.4 on 2023-01-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excercises', '0002_blanktext_exerciseset_text_delete_textblock_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['content_type', 'object_id'], name='excercises__content_746caf_idx'),
        ),
    ]
