# Generated by Django 4.1.5 on 2023-01-14 15:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('excercises', '0003_alter_exerciseset_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseset',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
