# Generated by Django 4.1.5 on 2023-01-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('excercises', '0004_exerciseset_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseset',
            name='categories',
            field=models.ManyToManyField(to='categories.category'),
        ),
        migrations.AddField(
            model_name='exerciseset',
            name='description',
            field=models.TextField(default='description', max_length=1000),
            preserve_default=False,
        ),
    ]
