# Generated by Django 4.1.4 on 2023-01-02 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excercises', '0004_remove_content_excercises__content_746caf_idx_and_more'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='content',
            index_together=set(),
        ),
    ]
