# Generated by Django 4.1.4 on 2023-01-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excercises', '0005_exerciseset_categories_exerciseset_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseset',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
