# Generated by Django 4.1.4 on 2023-01-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_popularity'),
        ('excercises', '0006_exerciseset_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseset',
            name='categories',
            field=models.ManyToManyField(blank=True, to='categories.category'),
        ),
    ]
