# Generated by Django 4.1.4 on 2023-01-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
    ]
