# Generated by Django 4.1.4 on 2023-02-11 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_popularity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-popularity',)},
        ),
    ]
