# Generated by Django 4.1.4 on 2023-02-11 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examsession',
            name='end_at',
        ),
        migrations.RemoveField(
            model_name='examsession',
            name='start_at',
        ),
    ]
