# Generated by Django 4.1.4 on 2023-02-11 12:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_remove_examsession_end_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='end_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='examsession',
            name='start_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
