# Generated by Django 4.1.4 on 2023-02-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_alter_exam_end_at_alter_exam_start_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionanswer',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
