# Generated by Django 4.1.4 on 2023-02-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_examsession_end_at_examsession_start_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
