# Generated by Django 4.1.4 on 2023-02-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_sessionanswer_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionanswer',
            name='points',
        ),
        migrations.AddField(
            model_name='examsession',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
