# Generated by Django 4.1.4 on 2023-02-12 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excercises', '0007_alter_exerciseset_categories'),
        ('exams', '0004_alter_exam_slug_alter_examsession_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionanswer',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excercises.content'),
        ),
    ]
