# Generated by Django 4.1.4 on 2023-02-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_exam_end_at_exam_start_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='start_at',
            field=models.DateTimeField(blank=True),
        ),
    ]
