# Generated by Django 4.1.4 on 2023-02-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_alter_exam_start_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
